{
  description = "ssolo flake";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs?ref=nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    zig2nix.url = "github:Cloudef/zig2nix";
  };

  outputs = { self, nixpkgs, flake-utils, zig2nix }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        env = zig2nix.outputs.zig-env.${system} { };

        sokol-shdc = pkgs.stdenv.mkDerivation {
          name = "sokol-shdc";
          version = "unstable";

          src = pkgs.fetchurl {
            url =
              "https://github.com/floooh/sokol-tools-bin/raw/master/bin/linux/sokol-shdc";
            sha256 = "1qpm8rp1dgidllq563njwrjrg1w2nk9j4akvjc0qhjhxqj60pi8x";
          };

          dontUnpack = true;

          installPhase = ''
            mkdir -p $out/bin
            cp $src $out/bin/sokol-shdc
            chmod +x $out/bin/sokol-shdc
          '';
        };

        buildInputs = with pkgs; [
          sokol-shdc
          xorg.libX11
          xorg.libXi
          xorg.libXcursor
          libGL
          alsa-lib
        ];
      in {
        # Dependencies are now prefetched via build.zig.zon.nix generated by zon2nix
        packages.default = env.package {
          src = ./.;
          pname = "ssolo";
          version = "0.0.0";
          zigPreferMusl = false;
          zigDisableWrap = false;
          nativeBuildInputs = [ sokol-shdc pkgs.pkg-config ];
          buildInputs = with pkgs; [
            xorg.libX11
            xorg.libXi
            xorg.libXcursor
            libGL
            alsa-lib
          ];
          postConfigure = ''
            export NIX_LDFLAGS="$NIX_LDFLAGS -L${pkgs.alsa-lib}/lib"
          '';
        };

        devShells.default = pkgs.mkShell {
          inherit buildInputs;

          shellHook = ''
            exec ${pkgs.zsh}/bin/zsh
          '';
        };
      });
}
